# Generated by Django 5.0.6 on 2024-06-24 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('insert_user', models.CharField(max_length=128)),
                ('insert_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=128)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('order_header_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cost_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_shipping', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_count', models.IntegerField()),
                ('vendor_order_id', models.CharField(max_length=128)),
                ('order_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('insert_user', models.CharField(max_length=128)),
                ('insert_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=128)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('raw_material_id', models.IntegerField(primary_key=True, serialize=False)),
                ('raw_material_description', models.CharField(max_length=512)),
                ('raw_material_short_name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeHeader',
            fields=[
                ('insert_user', models.CharField(max_length=128)),
                ('insert_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=128)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('recipe_header_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=64)),
                ('recipe_description', models.CharField(max_length=256)),
                ('yield_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('yield_uom', models.CharField(choices=[('PC', 'Piece'), ('UNIT', 'Unit'), ('LB', 'Pound'), ('OZ', 'Ounce'), ('FLOZ', 'Fluid Ounce'), ('YD', 'Yard'), ('IN', 'Inch'), ('THOU', 'Thousandth-inch'), ('G', 'Gram'), ('KG', 'Kilogram'), ('MG', 'Milligram'), ('M', 'Meter'), ('CM', 'Centimeter'), ('MM', 'Millimeter'), ('L', 'Liter'), ('ML', 'Milliliter'), ('CL', 'Centiliter'), ('DL', 'Deciliter')], max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('insert_user', models.CharField(max_length=128)),
                ('insert_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=128)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('vendor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('insert_user', models.CharField(max_length=128)),
                ('insert_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=128)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('order_line_item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_count', models.IntegerField()),
                ('sku', models.CharField(max_length=128)),
                ('upc', models.CharField(max_length=128)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_uom', models.CharField(choices=[('PC', 'Piece'), ('UNIT', 'Unit'), ('LB', 'Pound'), ('OZ', 'Ounce'), ('FLOZ', 'Fluid Ounce'), ('YD', 'Yard'), ('IN', 'Inch'), ('THOU', 'Thousandth-inch'), ('G', 'Gram'), ('KG', 'Kilogram'), ('MG', 'Milligram'), ('M', 'Meter'), ('CM', 'Centimeter'), ('MM', 'Millimeter'), ('L', 'Liter'), ('ML', 'Milliliter'), ('CL', 'Centiliter'), ('DL', 'Deciliter')], max_length=4)),
                ('order_header_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_api.orderheader')),
                ('raw_material_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_api.rawmaterial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeCost',
            fields=[
                ('insert_user', models.CharField(max_length=128)),
                ('insert_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_user', models.CharField(max_length=128)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('recipe_cost_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recipe_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('recipe_uom', models.CharField(choices=[('PC', 'Piece'), ('UNIT', 'Unit'), ('LB', 'Pound'), ('OZ', 'Ounce'), ('FLOZ', 'Fluid Ounce'), ('YD', 'Yard'), ('IN', 'Inch'), ('THOU', 'Thousandth-inch'), ('G', 'Gram'), ('KG', 'Kilogram'), ('MG', 'Milligram'), ('M', 'Meter'), ('CM', 'Centimeter'), ('MM', 'Millimeter'), ('L', 'Liter'), ('ML', 'Milliliter'), ('CL', 'Centiliter'), ('DL', 'Deciliter')], max_length=4)),
                ('raw_material_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_api.rawmaterial')),
                ('recipe_header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.recipeheader')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='orderheader',
            name='vendor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_api.vendor'),
        ),
    ]
