# Generated by Django 5.0.6 on 2025-03-06 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_unit_name', models.CharField(max_length=32)),
                ('to_unit_name', models.CharField(max_length=32)),
                ('multiply_by', models.DecimalField(decimal_places=10, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='BOMHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('output_quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('output_uom', models.CharField(choices=[('C', 'Cup'), ('CL', 'Centiliter'), ('CM', 'Centimeter'), ('DL', 'Deciliter'), ('FLOZ', 'Fluid Ounce (volume)'), ('G', 'Gram'), ('IN', 'Inch'), ('KG', 'Kilogram'), ('L', 'Liter'), ('LB', 'Pound'), ('M', 'Meter'), ('MG', 'Milligram'), ('ML', 'Milliliter'), ('MM', 'Millimeter'), ('OZ', 'Dry Ounce (weight)'), ('PC', 'Piece'), ('TBSP', 'Tablespoon'), ('THOU', 'Thousandth-inch'), ('TSP', 'Teaspoon'), ('UNIT', 'Unit'), ('YD', 'Yard')], max_length=4)),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BOOHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('bom_header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_api.bomheader')),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=512)),
                ('short_name', models.CharField(max_length=64)),
                ('bom_header', models.ForeignKey(blank=True, help_text='Link to the Bill of Materials if this item is manufactured internally.', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.bomheader')),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=14)),
                ('uom', models.CharField(choices=[('C', 'Cup'), ('CL', 'Centiliter'), ('CM', 'Centimeter'), ('DL', 'Deciliter'), ('FLOZ', 'Fluid Ounce (volume)'), ('G', 'Gram'), ('IN', 'Inch'), ('KG', 'Kilogram'), ('L', 'Liter'), ('LB', 'Pound'), ('M', 'Meter'), ('MG', 'Milligram'), ('ML', 'Milliliter'), ('MM', 'Millimeter'), ('OZ', 'Dry Ounce (weight)'), ('PC', 'Piece'), ('TBSP', 'Tablespoon'), ('THOU', 'Thousandth-inch'), ('TSP', 'Teaspoon'), ('UNIT', 'Unit'), ('YD', 'Yard')], max_length=4)),
                ('bom_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.bomheader')),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_api.material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=3000)),
                ('sequence_number', models.PositiveSmallIntegerField()),
                ('estimated_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('time_uom', models.CharField(blank=True, max_length=10, null=True)),
                ('boo_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.booheader')),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('cost_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_shipping', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_count', models.IntegerField()),
                ('vendor_order_id', models.CharField(max_length=128)),
                ('order_date', models.DateField()),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('item_count', models.IntegerField()),
                ('sku', models.CharField(blank=True, max_length=128)),
                ('upc', models.CharField(blank=True, max_length=128)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_uom', models.CharField(choices=[('C', 'Cup'), ('CL', 'Centiliter'), ('CM', 'Centimeter'), ('DL', 'Deciliter'), ('FLOZ', 'Fluid Ounce (volume)'), ('G', 'Gram'), ('IN', 'Inch'), ('KG', 'Kilogram'), ('L', 'Liter'), ('LB', 'Pound'), ('M', 'Meter'), ('MG', 'Milligram'), ('ML', 'Milliliter'), ('MM', 'Millimeter'), ('OZ', 'Dry Ounce (weight)'), ('PC', 'Piece'), ('TBSP', 'Tablespoon'), ('THOU', 'Thousandth-inch'), ('TSP', 'Teaspoon'), ('UNIT', 'Unit'), ('YD', 'Yard')], max_length=4)),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_api.material')),
                ('order_header', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_api.orderheader')),
                ('owner_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('production_date', models.DateField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('bom_header', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend_api.bomheader')),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=14)),
                ('uom', models.CharField(choices=[('C', 'Cup'), ('CL', 'Centiliter'), ('CM', 'Centimeter'), ('DL', 'Deciliter'), ('FLOZ', 'Fluid Ounce (volume)'), ('G', 'Gram'), ('IN', 'Inch'), ('KG', 'Kilogram'), ('L', 'Liter'), ('LB', 'Pound'), ('M', 'Meter'), ('MG', 'Milligram'), ('ML', 'Milliliter'), ('MM', 'Millimeter'), ('OZ', 'Dry Ounce (weight)'), ('PC', 'Piece'), ('TBSP', 'Tablespoon'), ('THOU', 'Thousandth-inch'), ('TSP', 'Teaspoon'), ('UNIT', 'Unit'), ('YD', 'Yard')], max_length=4)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_api.material')),
                ('production_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='backend_api.productionorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_dttm', models.DateTimeField(auto_now_add=True)),
                ('update_dttm', models.DateTimeField(auto_now=True)),
                ('vendor_name', models.CharField(max_length=256)),
                ('insert_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='orderheader',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_api.vendor'),
        ),
        migrations.AddConstraint(
            model_name='orderheader',
            constraint=models.UniqueConstraint(fields=('owner_user_id', 'vendor', 'cost_total'), name='unique_order_header_per_user_vendor_cost'),
        ),
    ]
