# Generated by Django 5.0.6 on 2024-06-24 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_alter_batch_insert_user_alter_batch_update_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderheader',
            constraint=models.UniqueConstraint(fields=('owner_user_id', 'cost_total', 'vendor'), name='unique_order_header_per_user_vendor_cost'),
        ),
    ]
