# Generated by Django 5.0.6 on 2024-06-24 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_orderheader_unique_order_header_per_user_vendor_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderheader',
            name='unique_order_header_per_user_vendor_cost',
        ),
        migrations.AddConstraint(
            model_name='orderheader',
            constraint=models.UniqueConstraint(fields=('owner_user_id', 'cost_total', 'vendor'), name='unique_order_header_per_user_vendor_cost', violation_error_code=1, violation_error_message='bloloboobloobl'),
        ),
    ]
