# Generated by Django 5.0.6 on 2024-06-24 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_remove_orderheader_unique_order_header_per_user_vendor_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderheader',
            name='unique_order_header_per_user_vendor_cost',
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='sku',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='upc',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='orderheader',
            constraint=models.UniqueConstraint(fields=('owner_user_id', 'cost_total', 'vendor'), name='unique_order_header_per_user_vendor_cost'),
        ),
    ]
