# Generated by Django 5.0.6 on 2024-06-26 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_remove_orderheader_unique_order_header_per_user_vendor_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecost',
            name='recipe_uom',
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='recipe_header_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.recipeheader'),
        ),
        migrations.AddField(
            model_name='recipecost',
            name='recipe_amount_uom',
            field=models.CharField(choices=[('C', 'Cup'), ('CL', 'Centiliter'), ('CM', 'Centimeter'), ('DL', 'Deciliter'), ('FLOZ', 'Fluid Ounce'), ('G', 'Gram'), ('IN', 'Inch'), ('KG', 'Kilogram'), ('L', 'Liter'), ('LB', 'Pound'), ('M', 'Meter'), ('MG', 'Milligram'), ('ML', 'Milliliter'), ('MM', 'Millimeter'), ('OZ', 'Ounce'), ('PC', 'Piece'), ('TBSP', 'Tablespoon'), ('THOU', 'Thousandth-inch'), ('TSP', 'Teaspoon'), ('UNIT', 'Unit'), ('YD', 'Yard')], default=None, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='unit_uom',
            field=models.CharField(choices=[('C', 'Cup'), ('CL', 'Centiliter'), ('CM', 'Centimeter'), ('DL', 'Deciliter'), ('FLOZ', 'Fluid Ounce'), ('G', 'Gram'), ('IN', 'Inch'), ('KG', 'Kilogram'), ('L', 'Liter'), ('LB', 'Pound'), ('M', 'Meter'), ('MG', 'Milligram'), ('ML', 'Milliliter'), ('MM', 'Millimeter'), ('OZ', 'Ounce'), ('PC', 'Piece'), ('TBSP', 'Tablespoon'), ('THOU', 'Thousandth-inch'), ('TSP', 'Teaspoon'), ('UNIT', 'Unit'), ('YD', 'Yard')], max_length=4),
        ),
        migrations.AlterField(
            model_name='recipeheader',
            name='yield_uom',
            field=models.CharField(choices=[('C', 'Cup'), ('CL', 'Centiliter'), ('CM', 'Centimeter'), ('DL', 'Deciliter'), ('FLOZ', 'Fluid Ounce'), ('G', 'Gram'), ('IN', 'Inch'), ('KG', 'Kilogram'), ('L', 'Liter'), ('LB', 'Pound'), ('M', 'Meter'), ('MG', 'Milligram'), ('ML', 'Milliliter'), ('MM', 'Millimeter'), ('OZ', 'Ounce'), ('PC', 'Piece'), ('TBSP', 'Tablespoon'), ('THOU', 'Thousandth-inch'), ('TSP', 'Teaspoon'), ('UNIT', 'Unit'), ('YD', 'Yard')], max_length=4),
        ),
    ]
