# Generated by Django 5.0.6 on 2024-06-26 18:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_remove_recipecost_recipe_uom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeCost',
            new_name='RecipeAmount',
        ),
    ]
