# Generated by Django 5.0.6 on 2024-06-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_rename_recipecost_recipeamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeamount',
            name='recipe_amount',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
    ]
