# Generated by Django 5.0.6 on 2024-06-26 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_alter_recipeamount_recipe_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orderheader',
            name='unique_order_header_per_user_vendor_cost',
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='unit_uom',
            field=models.CharField(choices=[('C', 'Cup'), ('CL', 'Centiliter'), ('CM', 'Centimeter'), ('DL', 'Deciliter'), ('FLOZ', 'Fluid Ounce (volume)'), ('G', 'Gram'), ('IN', 'Inch'), ('KG', 'Kilogram'), ('L', 'Liter'), ('LB', 'Pound'), ('M', 'Meter'), ('MG', 'Milligram'), ('ML', 'Milliliter'), ('MM', 'Millimeter'), ('OZ', 'Dry Ounce (weight)'), ('PC', 'Piece'), ('TBSP', 'Tablespoon'), ('THOU', 'Thousandth-inch'), ('TSP', 'Teaspoon'), ('UNIT', 'Unit'), ('YD', 'Yard')], max_length=4),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='recipe_header_id',
            field=models.ForeignKey(help_text='Use this field if one of your recipes is a raw material ingredient for a subsequent recipe (e.g. making a frosting to put on a cake)', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.recipeheader'),
        ),
        migrations.AlterField(
            model_name='recipeamount',
            name='recipe_amount_uom',
            field=models.CharField(choices=[('C', 'Cup'), ('CL', 'Centiliter'), ('CM', 'Centimeter'), ('DL', 'Deciliter'), ('FLOZ', 'Fluid Ounce (volume)'), ('G', 'Gram'), ('IN', 'Inch'), ('KG', 'Kilogram'), ('L', 'Liter'), ('LB', 'Pound'), ('M', 'Meter'), ('MG', 'Milligram'), ('ML', 'Milliliter'), ('MM', 'Millimeter'), ('OZ', 'Dry Ounce (weight)'), ('PC', 'Piece'), ('TBSP', 'Tablespoon'), ('THOU', 'Thousandth-inch'), ('TSP', 'Teaspoon'), ('UNIT', 'Unit'), ('YD', 'Yard')], max_length=4),
        ),
        migrations.AlterField(
            model_name='recipeheader',
            name='yield_uom',
            field=models.CharField(choices=[('C', 'Cup'), ('CL', 'Centiliter'), ('CM', 'Centimeter'), ('DL', 'Deciliter'), ('FLOZ', 'Fluid Ounce (volume)'), ('G', 'Gram'), ('IN', 'Inch'), ('KG', 'Kilogram'), ('L', 'Liter'), ('LB', 'Pound'), ('M', 'Meter'), ('MG', 'Milligram'), ('ML', 'Milliliter'), ('MM', 'Millimeter'), ('OZ', 'Dry Ounce (weight)'), ('PC', 'Piece'), ('TBSP', 'Tablespoon'), ('THOU', 'Thousandth-inch'), ('TSP', 'Teaspoon'), ('UNIT', 'Unit'), ('YD', 'Yard')], max_length=4),
        ),
        migrations.AddConstraint(
            model_name='orderheader',
            constraint=models.UniqueConstraint(fields=('owner_user_id', 'vendor', 'cost_total'), name='unique_order_header_per_user_vendor_cost'),
        ),
    ]
