# Generated by Django 5.0.6 on 2024-06-28 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0009_remove_orderheader_unique_order_header_per_user_vendor_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_unit_name', models.CharField(max_length=32)),
                ('to_unit_name', models.CharField(max_length=32)),
                ('multiply_by', models.DecimalField(decimal_places=10, max_digits=16)),
            ],
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='recipe_header_id',
            field=models.ForeignKey(help_text='Use this field if this raw material is made from one of your recipes (e.g. frosting for a cake).', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.recipeheader'),
        ),
    ]
